### ISSUE TITLE
Splash screen is black even when theme is set to light

### ISSUE THREAD

**Issue by max-kyou** [osociety/vernet#153]
The pure black splash screen makes the startup animation less noticeable. It looks weird when the whole display suddenly turns to black.

I'm using an Android 11 device by the way.

Hoping this gets fixed.
Thank you.

Related: #133

**Comment by fenglilinglegeluan** [comment]
![1](https://github.com/osociety/vernet/assets/44286100/9248f8e6-1ebd-4d83-bcc2-48b976af0ab7)
wow.When I opened the full-screen settings, the display was normal! I'm so excited!

**Comment by git-elliot** [comment]
@fenglilinglegeluan you're welcome.
