### ISSUE TITLE
A splash not sowing up

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#17]
A splash screen is missing whenever loading the app.

I am getting this warning in the console window 

> W/FlutterActivityAndFragmentDelegate(17184): A splash screen was provided to Flutter, but this is deprecated. See [flutter.dev/go/android-splash-migration](https://docs.flutter.dev/development/ui/advanced/splash-screen#migrating-from-manifest--activity-defined-custom-splash-screens) for migration steps.

**Comment by antonio-pedro99** [comment]
is this issue still opened?

**Comment by guyluz11** [comment]
I think so, try to run the app and check if the error appears in your log.

If so it needs addressing, if not please report back so that I can close the issue.

Thanks

**Comment by antonio-pedro99** [comment]
I am doing so

**Comment by git-elliot** [comment]
I don't see this warning anymore.
