### ISSUE TITLE
Scan for devices broken

### ISSUE THREAD

**Issue by preheater** [osociety/vernet#197]
Hello,
when i press the scan for devices button on my pixel 8 pro android15 then the scan shows endless the loading ring. I get no results.
It seems that is not working after your last update. I am using your latest version. I have removed vernet and installed it again via f-droid.

**To Reproduce**
1. Go to 'main menu'
2. Click on 'scan for devices'
3. Wait for result
4. Endless loop with no results

**Expected behavior**
The list of devices in my network should be shown in an overview

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 8 pro]
 - OS: [e.g. android 15]
 - Browser [e.g. chrome]
 - Version [e.g.Version 130.0.6723.73
com.android.chrome ]

**Additional context**

**Comment by johgy** [comment]
Same problem here.
Can you indicate the last version working, so I can revert back to this one?

**Comment by preheater** [comment]
Like johgy mentioned 1.0.6 is also working for me

**Comment by git-elliot** [comment]
I was trying vernet on API 35, and it gives me results. Not sure what could be the problem so I gonna add a crash reporting tool. 
<img width="407" alt="Screenshot 2024-10-27 at 6 29 10 PM" src="https://github.com/user-attachments/assets/c530e804-ded2-4ffb-bb88-1baa13705931">

**Comment by pled** [comment]
Same problem here, pixel 6a running grapheneos Android 15, Vernet 1.0.8.
Endless scan with no result.

**Comment by demaniak** [comment]
Same problem on andoid 14 (Samsung Galaxy A33 5G)
Vernet 1.0.8 (from f-droid)

**Comment by git-elliot** [comment]
Update is live on play store 1.0.9+27

**Comment by preheater** [comment]
Hi, i have installed the playstore version 1.0.9+27 but the scan devices function is still not working. 
![Screenshot_20241104-090304](https://github.com/user-attachments/assets/9610d70b-1451-4d65-84a0-86c1cfa95960)
![Screenshot_20241104-085759](https://github.com/user-attachments/assets/a425fd39-fe3f-440d-b14c-04e6c0d46b41)

**Comment by git-elliot** [comment]
Can you show me your custom subnet value in settings?

**Comment by preheater** [comment]
@git-elliot i use the default settings that are used with the installation. 
![Screenshot_20241104-140700](https://github.com/user-attachments/assets/17105151-9073-4272-8474-0071bc45f5e1)

**Comment by pled** [comment]
Yes, same issue here with default setting and v1.0.9. Rolling back to 1.0.6 from f-droid which works.

**Comment by xcpn** [comment]
Just updated via F-Droid to v1.0.9, I'm on Android 13.

With default settings or by setting custom subnet to '192.168.1.0' I still get infinite loop waiting for scan results.

**Comment by preheater** [comment]
Same here

**Comment by git-elliot** [comment]
Can someone try and let me know if latest release fixes the issue? https://github.com/osociety/vernet/releases/tag/v1.0.9%2B28

**Comment by xcpn** [comment]
@git-elliot it now works, but I want to suggest some things.

- There is no device type identification based on MAC address, this is a must
- The scan now takes around 30 seconds to complete for me
- The notification channel has default name, maybe change it to something like "Scan results" but to be honest I think notifications are unnecessary
- Device addresses have a comma at the end for some reason

Here are 2 images regarding the last two.

![channel.jpg](https://github.com/user-attachments/assets/58897167-f518-4de1-9f39-33aa0195fd42)

![scan.jpg](https://github.com/user-attachments/assets/61aad7a2-b835-4421-9204-3dc4ec6b0821)

**Comment by pled** [comment]
I am sorry, but using latest version 1.0.9 (28) from f-droid , scan is still not working, at least for me. Using Pixel 6a running grapheneos Android 15. Endless scan with no result.
I can't reverse to 1.0.6 anymore due to filo mechanism in f-droid available versions.

**Comment by git-elliot** [comment]
@pled As this is an open source project, you probably need to run this app locally on your laptop in debug mode. Just install flutter and check what is the error logs. I am afraid that I can record logs from installed devices without f-droid policies being violated.

**Comment by pled** [comment]
GrapheneOS out of scope for an open source project ? Are you serious ? 

Anyway, my message is only FYI, and I am only trying to help. I can live for now with 1.0.6 which works perfectly for me.

As far as I can see, since 1.0.8, Vernet is compiled with Vernet, am I correct ? 
I look at `adb logcat` logs, and this is what I found, that could be of interest for you ? 

```
11-14 15:21:22.721 31578 31616 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Could not initialize IsarCore library for processor architecture "android_arm64". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
11-14 15:21:22.721 31578 31616 E flutter : Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found
11-14 15:21:22.721 31578 31616 E flutter : #0      initializeCoreBinary (package:isar/src/native/isar_core.dart:78)
11-14 15:21:22.721 31578 31616 E flutter : #1      openIsar (package:isar/src/native/open.dart:81)
11-14 15:21:22.721 31578 31616 E flutter : #2      Isar.open (package:isar/src/isar.dart:107)
11-14 15:21:22.721 31578 31616 E flutter : #3      IsarDatabaseService.open (package:vernet/services/impls/isar_database_service.dart:13)
11-14 15:21:22.721 31578 31616 E flutter : <asynchronous suspension>
11-14 15:21:22.721 31578 31616 E flutter : #4      ScanRepository.put (package:vernet/repository/scan_repository.dart:27)
11-14 15:21:22.721 31578 31616 E flutter : <asynchronous suspension>
11-14 15:21:22.721 31578 31616 E flutter : #5      DeviceScannerService.startNewScan (package:vernet/services/impls/device_scanner_service.dart:24)
11-14 15:21:22.721 31578 31616 E flutter : <asynchronous suspension>
11-14 15:21:22.721 31578 31616 E flutter : #6      HostScanBloc._startNewScanBuiltInIsolate (package:vernet/pages/host_scan_page/host_scan_bloc/host_scan_bloc.dart:88)
11-14 15:21:22.721 31578 31616 E flutter : <asynchronous suspension>
11-14 15:21:22.721 31578 31616 E flutter : #7      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:229)
11-14 15:21:22.721 31578 31616 E flutter : <asynchronous suspension>
11-14 15:21:22.721 31578 31616 E flutter : 
```

**Comment by demaniak** [comment]
Sadly, also still not working for me.
- samsung A33 5G
- Android 14
- Vernet 1.0.9 (f-droid)

**Comment by pled** [comment]
@git-elliot , thank you for looking into that. Good news below : 
I have tested v1.1.0 (versioncode 2029) using the apk you provide on Github, and scan works as expected. :+1: 
Then I tried again 1.0.9 from f-droid, and confirm it does not work.

**Comment by git-elliot** [comment]
@pled and others here in this thread please try new release and report your observations. Scan speed issue is fixed, actually it was UI rendering issue rather than core library issue that was causing the slowness.

**Comment by git-elliot** [comment]
I would appreciate if you guys can test pre-release builds for various platforms you own and provide feedback through discussions on that release.

**Comment by preheater** [comment]
Hi @git-elliot,
i have tested this version Vernet-v1.1.0+29-app-arm64-v8a-dev-release.apk on Pixel8Pro.
It's a little bid strange to explain.
1. deinstalled old version
2. installed version mentioned above
3. Delete memory and cache
4. Vernet hangs and show endless loading
5.
![Screenshot_20241116-173325](https://github.com/user-attachments/assets/a1ffba51-99e9-43bd-85a8-2e101b11880f)
6. Closing Vernet and starting it again
7. Scan for device is visible and scan works
8. Switch to another network and using the refresh button doesn't work. It shows the wrong network name. The scan it self works
