### ISSUE TITLE
Devices that are not pingable do not appear in the app

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#23]
Tested scanning with another application named `Net Analyzer` and it somehow found my iPad which wasn't listed in the Vernet search.

`Net Analyzer` is a closed source so I don't really know how it found my iPad but it does add labels to each device.
Bouth for the iPad and some Lenovo tablet it didn't show any labels (including the pingable label) and both of them didn't show on Vernet scan.

**Comment by guyluz11** [comment]
Also was using [lan_scanner](https://pub.dev/packages/lan_scanner) I managed to find iPad and IP and Lenovo tablet IPs.

**Comment by git-elliot** [comment]
I guess it's not a bug but rather added functionality to further discover devices using ARP table. Hence removing bug from label would be better.

**Comment by guyluz11** [comment]
I think this is a bug because the app network scan does not find all the devices it can scan.

We can also remove the bug label because it cloud count as a new feature that needs to be implemented.
Your choice.

**Comment by guyluz11** [comment]
Adding this quote from canonical developer

> to get this arp table on Linux you will need to make a [system call](https://man7.org/linux/man-pages/man7/arp.7.html) via FFI. Or find a package that does that

**Comment by git-elliot** [comment]
On desktop, we show devices from ARP table also. I can see our result set count is increased from past last year.
