### ISSUE TITLE
Missing functionality on ios? 

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#24]
I didn't test it on ios but Vernet uses [dart_ping](https://pub.dev/packages/dart_ping) which does not support ios.

> To use dart_ping on iOS, add the [dart_ping_ios](https://pub.dev/packages/dart_ping_ios) package as a dependency

And in the packages I can't find [dart_ping_ios](https://pub.dev/packages/dart_ping_ios) so I guess some functionality currently does not work on ios

**Comment by git-elliot** [comment]
We are using both `network_tools` and `dart_ping` in vernet. Let's focus on [network_tools_flutter](https://github.com/git-elliot/network_tools/issues/32) first

**Comment by git-elliot** [comment]
Please reopen if you think ping is not working on iOS
