### ISSUE TITLE
Scan for devices on app startup

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#37]
We can scan for devices in the network on app startup.

This way when opening the page it will already be loaded.

This is a thought and I would love to hear your opinion on that.

**Comment by git-elliot** [comment]
That can cause battery drain, I know ping operation 254 times will put lot of work on the OS even when the user doesn't want so.

**Comment by OmlineEditor** [comment]
this can be done but only with the option to enable or disable in the settings

**Comment by git-elliot** [comment]
Thanks for the suggestions @OmlineEditor
