### ISSUE TITLE
Get device info by Mac address

### ISSUE THREAD

**Issue by TBit-services** [osociety/vernet#42]
I love your blog app! 
And I have a future request :

Is it possible to get the device brand, type etc from there mac address for example with https://www.macvendorlookup.com/api/v2/{MAC_Address

Thanx for keep this in consideration!

Thomas

**Comment by guyluz11** [comment]
Hi and thank for using our app.

Currently our scan does not contain Mac address in most cases (only on Android 11 and lower), so there is more to be done before continuing and using something like acvendorlookup.com.

There is issue that is mentioning what you have asked but it is more general so I think it will be good to keep this issue open as sub issue to #6

**Comment by git-elliot** [comment]
Can we mark it as duplicate to #8

**Comment by git-elliot** [comment]
Getting mac address is only possible

**Comment by git-elliot** [comment]
Getting mac address is only possible
