### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#44]
Please update all project dependencies to the last version.

**Comment by superiorsd10** [comment]
@guyluz11 Can I work on this issue?

**Comment by guyluz11** [comment]
Sure

**Comment by git-elliot** [comment]
This should be linked, so that github closes it automatically.

**Comment by guyluz11** [comment]
> This should be linked, so that github closes it automatically.

Not sure what do you mean by linking but just that you know users can't change the value here

![image](https://user-images.githubusercontent.com/9304740/193481648-ea04c226-fede-4beb-8502-e750d0f947b3.png)

**Comment by git-elliot** [comment]
Okay I'll link the issue in PR, before merging it
