### ISSUE TITLE
Add git action to check if project is compiling 

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#46]
Currently, there isn't an automatic way for the project to check if it is getting compiled for each new pr.

For that we need a git action that checks
1. If the project is compiling.
2. Project tests are passing.

I have done it before so you can use my version and tweak it a little bit.
Make sure that there is at least one test and all the tests are passing, if there is no test create one that just passes for the automation to work.

Link to my git action that works (for a flutter project)
https://github.com/CyBear-Jinni/cbj_app/blob/master/.github/workflows/dart.yml

**Comment by git-elliot** [comment]
I guess it's already there as a half steps in [.github/workflows/flutter_release.yml](https://github.com/osociety/vernet/blob/main/.github/workflows/flutter-release.yml). One just need to strip the code out till the "Run tests" step
