### ISSUE TITLE
Remove analyzer warnings

### ISSUE THREAD

**Issue by git-elliot** [osociety/vernet#47]
Public method documentation can be removed from lint as per now from [analysis_options.yml](https://github.com/osociety/vernet/blob/main/analysis_options.yaml).

**Comment by guyluz11** [comment]
I think it is basically just removing the line 

```
    # Good packages document everything
    public_member_api_docs: true
```

**Comment by superiorsd10** [comment]
@guyluz11 I would like to work on this issue. Can you please assign it to me?

**Comment by guyluz11** [comment]
> @guyluz11 I would like to work on this issue. Can you please assign it to me?

It looks like someone took this issue already, we have just forgot to assign it to him

**Comment by JSmurf** [comment]
I will take care of this.

**Comment by JSmurf** [comment]
Apologies for setting my initial PR to main.

**Comment by git-elliot** [comment]
> Apologies for setting my initial PR to main.

It's okay since default branch is set to main, it happened. Let me change it to dev.

**Comment by guyluz11** [comment]
@git-elliot main should stay as the default branch.

But there is a way to make pr open automatically to dev and this is what we need.
Update me if you find how, I need it to for other projects.
