### ISSUE TITLE
flavorDimensions in android is deprecated

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#66]
It looks like flavorDimensions  got deprecated and should be replaced with list of the flavors

https://stackoverflow.com/questions/75100286/android-flavordimensions-is-deprecated

So this line
https://github.com/osociety/vernet/blob/52bf1564bd4cbc2e3bc82b1b559f7f886ecb1701/android/app/build.gradle#L65

Should be replaced with 
`flavorDimensions ["deploy"]`

**Comment by git-elliot** [comment]
Fixed
