### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [osociety/vernet#75]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3962113951#L699

So I tried 3.3.10 or 3.7.7 just to see
```
Error: Couldn't resolve the package 'awesome' in 'package:awesome/awesome.module.dart'.
lib/injection.config.dart:8:8: Error: Not found: 'package:awesome/awesome.module.dart'
import 'package:awesome/awesome.module.dart' as _i3;
       ^
lib/injection.config.dart:28:15: Error: Method not found: 'AwesomePackageModule'.
    await _i3.AwesomePackageModule().init(gh);
              ^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aawesome%2Fawesome.module.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:625:9)
<asynchronous suspension>
#4      starter (package:frontend_server/frontend_server.dart:1451:12)
<asynchronous suspension>
#5      main (file:///b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
<asynchronous suspension>



FAILURE: Build failed with an exception.

* Where:
Script '/home/vagrant/build/srclib/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159
```

Thoughts?

Also, any chance you could set Flutter as a submodule in your repo? It will erase the need to open manual MRs as you control the version directly. 

ref: https://git-scm.com/book/en/v2/Git-Tools-Submodules

and ref: https://gitlab.com/fdroid/fdroiddata/-/blob/master/templates/build-flutter.yml

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/af133f465d86750cd9eb6a93548c5da3187fc37d

**Comment by git-elliot** [comment]
It builds fine in github actions and in local, I'm investigating by running fdroid build locally.

**Comment by git-elliot** [comment]
and also I verified that i'm not using any package `awesome`, I don't know from where fdroid is pulling it.

**Comment by kostadin24** [comment]
injection.config.dart is not autogenerated when try to build project.

**Comment by licaon-kter** [comment]
How do you build exactly?

**Comment by kostadin24** [comment]
> How do you build exactly?

Got project from github. Started debug.

**Comment by licaon-kter** [comment]
Now translate that please :)

Start what where how?

**Comment by kostadin24** [comment]
In Android Studio pressed debug.

**Comment by licaon-kter** [comment]
F-Droid uses the command line tools as Android Studio is not (afaik) FOSS.

When using that, we see the errors above.

**Comment by git-elliot** [comment]
@licaon-kter last build got succeeded for 1.0.1+16

**Comment by licaon-kter** [comment]
pls reopen 

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7699751437#L1151 

ref: https://github.com/osociety/vernet/blob/v1.0.8%2B26/pubspec.yaml#L36 is not FOSS

ref: https://github.com/britannio/in_app_review/blob/master/in_app_review/android/build.gradle#L51-L55

**Comment by linsui** [comment]
@git-elliot Please add the pubspec.lock file in the repo so that we can rebuild the same apk.

**Comment by git-elliot** [comment]
@linsui Added in release 1.0.9+27

**Comment by linsui** [comment]
Thanks!
