### ISSUE TITLE
mDNS devices are missing

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#81]
After last updates it seems that mDNS does not get shown anymore.

**Comment by guyluz11** [comment]
I think there is a package to catch Network requests and then mimic response.
Maybe it could be used for us to mimic device mdns response and then checking if it returned correctly

**Comment by git-elliot** [comment]
It is like some mock server responses, right?

**Comment by guyluz11** [comment]
This is using mock data but we use the same requests outside and catch them using it
