### ISSUE TITLE
Upi & bitcoin address

### ISSUE THREAD

**Issue by ghost** [osociety/vernet#83]
If possible add on Upi & bitcoin https://github.com/osociety/vernet#support-and-donate given @ https://fsoc13ty.blogspot.com/p/vernet-network-analyzer-and-monitoring.html

**Comment by git-elliot** [comment]
I am thinking of removing https://fsoc13ty.blogspot.com/p/vernet-network-analyzer-and-monitoring.html and can't provide QRcode for donations, because then I won't be able to track automatically how much people donated.
