### ISSUE TITLE
add Liberapay, ko-fi on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [osociety/vernet#84]
@git-elliot 
* **your explicit consent is required** to add Liberapay ```https://liberapay.com/OpenSociety/donate``` & ```https://ko-fi.com/fs0c13ty```  given at https://github.com/osociety/vernet#support-and-donate in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/HEAD/metadata/org.fsociety.vernet.yml)
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by git-elliot** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14832

**Comment by git-elliot** [comment]
It will be fetched automatically from .github/funding.yml
