### ISSUE TITLE
Wi-Fi name including quotes

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#93]
Wi-Fi name should not include `"`

![Screenshot_20231221_094507](https://github.com/osociety/vernet/assets/9304740/2a9e16a2-e627-4546-b4e6-a9dfcceb052d)

**Comment by git-elliot** [comment]
Is your wifi name in android settings is `"amiuzz"` or `amiuzz`

**Comment by guyluz11** [comment]
`amiuz2` 
The " is from the package we use for getting wifi SSID name
