### ISSUE TITLE
Running on Linux - report

### ISSUE THREAD

**Issue by LFd3v** [osociety/vernet#95]
First of all, thank you for developing and providing this nice app for free.

I was looking for a native network scanner for Linux with a nice GUI, and Vernet fits the requirements very well.

I downloaded the latest Linux version from Releases (Vernet-v1.0.1+16-linux.zip), unpacked it and then tried to run the app, but all I got was a blank screen. Then I started it from the terminal and I saw an error complaining about not being able to run `arp`. On Ubuntu 23.10 it is not installed by default, but after installing **net-tools**, which includes `arp`, the app worked fine. So probably it is a good idea to state somewhere that `arp` (and any other required package) needs to be installed for the app to run.

I was also able to create a simple .desktop file to integrate the app with the DE:

```
[Desktop Entry]
Version=1.1
Type=Application
Name=Vernet
Comment=Network analyzer and monitoring tool
Icon=/home/user/Applications/Vernet-v1.0.1+16-linux/vernet.png
Exec=/home/user/Applications/Vernet-v1.0.1+16-linux/vernet
Path=/home/user/Applications/Vernet-v1.0.1+16-linux
Actions=
Categories=Monitor;Network;
Keywords=network;scanner;
StartupNotify=true
StartupWMClass=vernet
```

For the icon, I used [ic_launcher_round.png](https://github.com/osociety/vernet/blob/dev/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png).

Besides this, some remarks/suggestions:

1. It would be nice if the app saved the window size (right now it always starts in full screen mode);
2. Update the [project homepage](https://fsoc13ty.blogspot.com/p/vernet-network-analyzer-and-monitoring.html) to reflect that the Linus and Win versions are available;
3. The speed test should denote that it would open a link with the default browser (like adding a shortcut/link icon to the right of the button), or, better yet, open the link in a web view inside the app (not sure how Flutter would handle this on different platforms tho);
4. As asked in #94, it would be nice to explain what and when it connects to the internet (I am assuming it just downloads some files to run the app, and also check for updates?).

Please feel free to ask for more info or tests if needed.

Thanks again. Regards.

<details><summary>Screenshot</summary>

![Screenshot from 2024-01-20 23-18-56](https://github.com/osociety/vernet/assets/146497073/6efa903f-bb2b-4aba-bc45-b4efab64e7db)

</details>

**Comment by guyluz11** [comment]
Cool nice work

I think it should work also without arp even though it increase functionality.
Also it could be published on the snap store for easy installation.

**Comment by LFd3v** [comment]
Please avoid Snaps, specially if you guys favor FOSS (the server/management of Snaps is closed source). I think a better option would be AppImage, specially because it seems that Flutter does not have many dependencies), or at most FlatPak.

Cheers

**Comment by guyluz11** [comment]
> Please avoid Snaps, specially if you guys favor FOSS (the server/management of Snaps is closed source). I think a better option would be AppImage, specially because it seems that Flutter does not have many dependencies), or at most FlatPak.
> 
> Cheers

I think it is wise to publish where we can and not only where it is 100% FOSS, by that logic it should also be removed from palystory and appstore.
But this is choice is probably more opinion based.
I've uploaded some snaps and can say that it was straightforward so I can help where I have experience.

**Comment by git-elliot** [comment]
@LFd3v Thank you very much for testing the linux app, honestly I didn't tested linux bundle at all. I am glad that it works at least. I will add this issue to our git project to work on it.

**Comment by LFd3v** [comment]
Hi, there. I just though you may want to know that the Linux build from [1.0.3+18](https://github.com/osociety/vernet/releases/tag/1.0.3+18) actually has the 1.0.2+17 version.

Cheers

**Comment by git-elliot** [comment]
I linked two sub issues to track the further progress of what you have requested. All the other points are taken up and fixed already. 
Thanks.
